language: cpp

branches:
  only:
   - master

before_install:
  - uname -m
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install nasm:i386 gcc-multilib g++-multilib

script:
  - chmod +x build_updateable_elf.sh
  - ./build_updateable_elf.sh
