language: cpp

branches:
  only:
   - master

before_install:
  - chmod +x version_make_progress.sh
  - chmod +x build_updateable_elf.sh

#  - chmod +x ./plugins/antinamechange/makedll32
#  - chmod +x ./plugins/antinamesteal/makedll32
  - chmod +x ./plugins/antispam/makedll32
#  - chmod +x ./plugins/censor/makedll32
#  - chmod +x ./plugins/clan-tag-protection/makedll32
#  - chmod +x ./plugins/cpptest/makedll32
  
  - arch
  - sudo ls /etc/dpkg/dpkg.cfg.d/
  - sudo sh -c "echo 'foreign-architecture i386' > /etc/dpkg/dpkg.cfg.d/multiarch"
  - sudo ls /etc/dpkg/dpkg.cfg.d/
#  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - sudo apt-get install nasm:i386 gcc-multilib g++-multilib

script:
  
  - ./build_updateable_elf.sh
  
#  - ./plugins/antinamechange/makedll32
#  - ./plugins/antinamesteal/makedll32

  - cd plugins/antispam
  - ./makedll32
#  - ./plugins/censor/makedll32
#  - ./plugins/clan-tag-protection/makedll32
#  - ./plugins/cpptest/makedll32

  - cd ..

deploy:
  provider: releases
  api_key: "695b475fead9ee68ab20febbb4e8b6b92863be87"
  file: 
    - "bin/cod4x18_dedrun"
    - "plugins/antispam/antispam.so"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
