language: cpp

branches:
  only:
   - master

before_install:
  - arch
  - sudo ls /etc/dpkg/dpkg.cfg.d/
  - sudo sh -c "echo 'foreign-architecture i386' > /etc/dpkg/dpkg.cfg.d/multiarch"
#  - sudo dpkg --add-architecture i386
#  - sudo apt-get update
#  - sudo apt-get install nasm:i386 gcc-multilib g++-multilib

script:
  - chmod +x build_updateable_elf.sh
  - ./build_updateable_elf.sh
