version: 1.0.{build}
before_build:
- ps: >-
    Write-Host "Setting up MinGW environment:"

    Write-Host "    Downloading MinGW..."

    mkdir mingw | Out-Null
    
    curl -o mingw/binutils.tar.xz https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/binutils-2.24-1-mingw32-bin.tar.xz
    
    curl -o mingw/mingw-runtime-dev.tar.xz https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/mingwrt-3.21-mingw32-dev.tar.xz
    
    curl -o mingw/mingw-runtime-dll.tar.xz https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/mingwrt-3.21-mingw32-dll.tar.xz
    
    curl -o mingw/w32api.tar.xz https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/w32api-3.17-2-mingw32-dev.tar.lzma
    
    curl -o mingw/mpc.tar.xz https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/libmpc-0.8.1-1-mingw32-dll-2.tar.lzma
    
    curl -o mingw/mpfr.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/libmpfr-2.4.1-1-mingw32-dll-1.tar.lzma
    
    curl -o mingw/gmp.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/gmp-5.1.2-1-mingw32-dll.tar.lzma
    
    curl -o mingw/pthreads-dev.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/pthreads-w32-2.9.1-1-mingw32-dev.tar.lzma
    
    curl -o mingw/pthreads-dll.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/pthreads-w32-2.9.1-1-mingw32-dll.tar.lzma
    
    curl -o mingw/libiconv.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/libiconv-1.14-3-mingw32-dll.tar.lzma
    
    curl -o mingw/zlib.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/zlib-1.2.8-1-mingw32-dll.tar.lzma
    
    curl -o mingw/gettext.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/gettext-0.18.3.1-1-mingw32-dll.tar.lzma
    
    Write-Host "    Downloading gcc..."

    curl -o mingw/gcc-core-bin.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/gcc-core-4.8.1-4-mingw32-bin.tar.lzma
    
    curl -o mingw/gcc-core-dev.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/gcc-core-4.8.1-4-mingw32-dev.tar.lzma
    
    curl -o mingw/gcc-core-dll.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/gcc-core-4.8.1-4-mingw32-dll.tar.lzma
    
    Write-Host "    Downloading mingw32-make..."

    curl -o mingw/mingw32-make.tar.gz https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/mingw32-make-3.81-2.tar.gz
    
    Write-Host "    Downloading g++..."

    curl -o mingw/gcc-c++-bin.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/gcc-c++-4.8.1-4-mingw32-bin.tar.lzma

    curl -o mingw/gcc-c++-dev.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/gcc-c++-4.8.1-4-mingw32-dev.tar.lzma

    curl -o mingw/gcc-c++-dll.tar.lzma https://github.com/luzexi/MinGW/raw/master/x86/var/cache/mingw-get/packages/gcc-c++-4.8.1-4-mingw32-dll.tar.lzma

    Write-Host "    Downloading pexports..."

    curl -o mingw/pexports.tar.xz "http://vorboss.dl.sourceforge.net/project/mingw/MinGW/Extension/pexports/pexports-0.47/pexports-0.47-mingw32-bin.tar.xz"

    cd mingw
    
    ls

    Write-Host "    Installing MinGW..."

    7z x binutils.tar.xz | Out-Null

    7z x binutils.tar | Out-Null
    
    7z x mingw-runtime-dev.tar.xz | Out-Null
    
    7z x mingw-runtime-dev.tar | Out-Null
    
    7z x mingw-runtime-dll.tar.xz | Out-Null
    
    7z x mingw-runtime-dll.tar | Out-Null
    
    7z x w32api.tar.xz | Out-Null
    
    7z x w32api.tar | Out-Null
    
    7z x mpc.tar.xz | Out-Null
    
    7z x mpc.tar | Out-Null
    
    7z x mpfr.tar.lzma | Out-Null
    
    7z x mpfr.tar | Out-Null
    
    7z x gmp.tar.lzma | Out-Null
    
    7z x gmp.tar | Out-Null
    
    7z x pthreads-dev.tar.lzma | Out-Null
    
    7z x pthreads-dev.tar | Out-Null
    
    7z x pthreads-dll.tar.lzma | Out-Null
    
    7z x pthreads-dll.tar | Out-Null
    
    7z x libiconv.tar.lzma | Out-Null
    
    7z x libiconv.tar | Out-Null
    
    7z x zlib.tar.lzma | Out-Null
    
    7z x zlib.tar | Out-Null
    
    7z x gettext.tar.lzma | Out-Null
    
    7z x gettext.tar | Out-Null

    Write-Host "    Installing gcc..."
    
    7z x gcc-core-bin.tar.lzma | Out-Null
    
    7z x gcc-core-bin.tar | Out-Null
    
    7z x gcc-core-dev.tar.lzma | Out-Null
    
    7z x gcc-core-dev.tar | Out-Null
    
    7z x gcc-core-dll.tar.lzma | Out-Null
    
    7z x gcc-core-dll.tar | Out-Null

    Write-Host "    Installing mingw32-make..."
    
    7z x mingw32-make.tar.gz | Out-Null
    
    7z x mingw32-make.tar | Out-Null

    Write-Host "    Installing g++..."
    
    7z x gcc-c++-bin.tar.lzma | Out-Null
    
    7z x gcc-c++-bin.tar | Out-Null
    
    7z x gcc-c++-dev.tar.lzma | Out-Null
    
    7z x gcc-c++-dev.tar | Out-Null
    
    7z x gcc-c++-dll.tar.lzma | Out-Null
    
    7z x gcc-c++-dll.tar | Out-Null

    Write-Host "    Installing pexports..."

    7z x pexports.tar.xz | Out-Null

    7z x pexports.tar | Out-Null

    cd ..

    Write-Host "Setting up NASM:"

    Write-Host "    Downloading NASM..."

    curl -o nasminst.exe http://libgd.blob.core.windows.net/nasm/nasm-2.07-installer.exe

    Write-Host "    Installing NASM..."

    .\nasminst.exe /S

    Write-Host "Setting up environment variables."

    [Environment]::SetEnvironmentVariable("PATH",  "$pwd\mingw\bin;$pwd\bin;C:\Program Files (x86)\nasm;$($env:path)")

build_script:
- ps: >-
    Write-Host "Building server code:"

    Write-Host "    Building tomcrypt..."

    cd src/tomcrypt

    ./compile_win32.cmd | Out-Null

    Write-Host "    Building mbedtls..."

    cd ../mbedtls

    ./build.cmd  | Out-Null
    
    Write-Host "    Building cod4x18 server..."

    cd ../..

    mingw32-make.exe win32

    Write-Host "Done."
test_script:
- ps: ./bin/cod4x18_dedrun.exe
branches:
  only:
    - master    # Ignore all other branches.
artifacts: 
  - path: bin\cod4x18_dedrun.exe
    name: cod4exe
deploy:
- provider: GitHub
  auth_token:
    secure: Je7YohhSVawAyVkWQG3zyoppIB73CjJB99IlzzJzosFJ5NeBkYLUuA2SV52LTWXj
  artifact: cod4exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
